Changes some scm commands that are not supported in RTC scm tools 4.0.3
WtfJoke/rtc2git pull request #112
Opened 2016-11-05 02:03 UTC by z9944x

2016-11-05 15:50 UTC, WtfJoke requested changes
Thanks for your pull request. :)

Could you please check the comments and also run and fix the tests.

Thanks in advance!

2016-11-05 15:50 UTC, WtfJoke commented on rtcFunctions.py
> +        shell.execute("%s login -r %s -u %s -P \"%s\"" % (config.scmcommand, config.repo, config.user, config.password))
was it necessary to quote the password like this?

2016-11-05 15:50 UTC, WtfJoke commented on rtcFunctions.py
> +            shouter.shout(replacecommand)
I guess this can be removed?

2016-11-05 15:50 UTC, WtfJoke commented on rtcFunctions.py
> +            command = "scm --show-alias n --show-uuid y list baselines --components %s -r %s -u %s -P \"%s\" -m 20000" % \
quoting necessary?

2016-11-05 15:50 UTC, WtfJoke commented on config.ini.minimum.sample
> +# Stream to be migrated,  referenced by Name and UUID
Does name work also? From your answer I thought only UUID will work.
Else we could just write referenced by UUID

2016-11-05 15:50 UTC, WtfJoke commented on rtcFunctions.py
> +     ###   config.collectstreamuuids()
I would remove the line instead of commenting it out

2016-11-07 15:42 UTC, z9944x commented on rtcFunctions.py
> +            shouter.shout(replacecommand)
Yes

2016-11-07 15:43 UTC, z9944x commented on rtcFunctions.py
> +            command = "scm --show-alias n --show-uuid y list baselines --components %s -r %s -u %s -P \"%s\" -m 20000" % \
Tested on windows with a password that have space on it, double quotes are needed

2016-11-07 15:44 UTC, z9944x commented on config.ini.minimum.sample
> +# Stream to be migrated,  referenced by Name and UUID
We cannot found the UUID from the Stream name with the scm tools.  If we provide only the UUID and the streamname, the branch name on git will be the UUID instead of the nice name ( streamname )

2016-11-07 15:45 UTC, z9944x commented on rtcFunctions.py
> +     ###   config.collectstreamuuids()
yes

2016-11-07 15:46 UTC, z9944x commented on rtcFunctions.py
> +        shell.execute("%s login -r %s -u %s -P \"%s\"" % (config.scmcommand, config.repo, config.user, config.password))
Tested on windows with a password that have space on it, double quotes are needed

2016-11-15 11:20 UTC, WtfJoke commented
Thanks for the further adjustments. 👍

2016-11-15 11:20 UTC, merged

2019-01-25 17:18 UTC, WtfJoke commented
Just linking this to #102 and #130